### ISSUE TITLE
HELP_WANTED: update broken URLs

### ISSUE THREAD

**Issue by borgified** [vhf/free-programming-books#1586]
been a while since i checked our links so this is a big one. feel free to create pull requests to fix the problems shown below. you may also want to manually test the link in case it was temporarily down at the time of testing.

free-programming-interactive-tutorials-en.md
404 Not Found http://jhusain.github.io/learnrx/

free-programming-books-ja.md
500 Can't connect to www.narihiro.info:80 (Connection refused) http://www.narihiro.info/g1gc-impl-book/
404 Not Found http://rd.clojure-users.org/
500 Can't connect to www.doyouphp.jp:80 (Bad hostname) http://www.doyouphp.jp/book/book_phpdp.shtml
404 Not Found http://www4.ocn.ne.jp/~inukai/scheme_primer_j.html
404 Not Found http://karetta.jp/book-cover/gauche-hacks
404 Not Found http://gst.plasticheart.info/tutorial-c84

free-programming-books-gr.md

free-programming-books-tr.md
500 Internal Server Error http://www.kaanaslan.com/resource/course_note/download_file.php?file_id=16

free-programming-books-hu.md

free-programming-books.md
404 Not Found http://stackoverflow.com/revisions/392926/175
404 Not Found http://www.songho.ca/opengl/index.html):
404 Not Found http://see.stanford.edu/see/materials/aimlcs229/handouts.aspx
404 Not Found http://web.mit.edu/~holden1/www/math/number-theory.pdf
404 Not Found http://www.iitg.ac.in/kartha/CE601-14/CourseSchedule.htm),2014
404 Not Found http://cm.bell-labs.com/cm/ms/what/shannonday/paper.html
404 Not Found http://public.dhe.ibm.com/common/ssi/ecm/en/ram14011usen/RAM14011USEN.PDF
404 Not Found http://ftacademy.org/materials/fsm/11
403 Forbidden http://www.cs.jhu.edu/~scott/pl/book/dist/
500 Can't connect to www.advancedlinuxprogramming.com:80 (Connection refused) http://www.advancedlinuxprogramming.com/
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/20
404 Not Found http://www.cs.uwm.edu/~cs654/handouts/cool-manual.pdf
403 Forbidden http://media.developerforce.com/workbooks/HerokuPostgres_Workbooks_Web_Final.pdf
500 Can't connect to gradle.org:443 (certificate verify failed) http://www.gradleware.com/registered-access?content=books%2Fbuilding-and-testing%2F
404 OK http://spock-framework.readthedocs.org/en/latest/
404 Not Found http://www.astro.virginia.edu/class/oconnell/astr511/IDLresources/getting-started-IDL-v7.0.pdf
404 Not Found http://www.astro.virginia.edu/class/oconnell/astr511/IDLresources/IDLguide.html
404 Not Found http://www.rogerstokes.free-online.co.uk/book.htm
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/3
404 Not Found https://leanpub.com/hibernate4-example-programs
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/16
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/1
500 Service unavailable (with message) http://www.heatonresearch.com/articles/series/15
404 Not Found http://wicket.apache.org/guide/
404 Not Found http://jqfundamentals.com/book/
500 Can't connect to www.advancedlinuxprogramming.com:80 (Connection refused) http://www.advancedlinuxprogramming.com/
500 read timeout http://ocamlunix.forge.ocamlcore.org/
500 Can't connect to www.csupomona.edu:443 https://www.csupomona.edu/~jrfisher/www/prolog_tutorial/pt_framer.html
404 Not Found http://beastie.cs.ua.edu/cs150/book/index.html
500 Can't connect to readruby.io:80 (Bad hostname) http://readruby.io/
500 Can't connect to modular.math.washington.edu:80 (timeout) http://modular.math.washington.edu/books/sagebook/sagebook.pdf

javascript-frameworks-resources.md
404 Not Found http://dl.e-book-free.com/2013/07/knockoutjs_starter.pdf

free-programming-books-ru.md
404 Not Found http://www.soslan.ru/tcp/
400 Bad Request https://dl.dropboxusercontent.com/u/4606839/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0
404 Not Found http://ru.wikibooks.org/wiki/%D0

free-programming-books-pt_PT.md

free-programming-books-id.md
404 Not Found http://kristories.gitbooks.io/mongodb-untuk-indonesia/

free-programming-books-pt_BR.md
404 Not Found http://herberthamaral.com/posts/2013-02-25-sobre-o-jquery-fundamentals.html

free-programming-books-de.md
404 Not Found http://www.iaik.tugraz.at/content/teaching/bachelor_courses/betriebssysteme/downloads/schmaranz2.pdf

free-programming-books-sk.md

free-programming-books-se.md

free-programming-books-fr.md
404 Not Found http://framabook.org/histoires-et-cultures-du-libre/
404 Not Found http://framabook.org/option-libre-du-bon-usage-des-licences-libres/
404 Not Found http://framabook.org/8-produire-du-logiciel-libre/

free-programming-books-zh.md
500 Can't connect to www.coursera.org:443 https://www.coursera.org/courses?orderby=upcoming&lngs=zh
404 Not Found http://ocw.mit.edu/courses/translated-courses/simplified-chinese/
404 Not Found http://island205.github.io/tlboc/
404 Not Found https://www.gitbook.com/book/0532/nodejs/details)%EF
404 Not Found http://wusuopu.gitbooks.io/symfony2_tutorial/content
500 Can't connect to r6rs.mrliu.org:443 http://r6rs.mrliu.org/)%EF

free-programming-books-ro.md

free-programming-books-it.md

free-programming-books-az.md

free-programming-books-cs.md

free-courses-en.md

free-programming-books-es.md
404 Not Found http://docencia.izt.uam.mx/pece/pagina_academica/AA/indexa.html
404 Not Found http://www.aliatuniversidades.com.mx/bibliotecasdigitales/pdf/sistemas/Analisis_y_disenio_de_algoritmos.pdf
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-agile.pdf
404 Not Found http://savannah.nongnu.org/hg/?group=elisp-es
500 Can't connect to gitimmersion.mx:80 (Bad hostname) http://gitimmersion.mx
500 Can't connect to library.originalhacker.org:80 (Bad hostname) http://library.originalhacker.org/biblioteca/articulo/ver/123
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-php.pdf
500 Can't connect to flanagan.ugr.es:80 (timeout) http://flanagan.ugr.es/perl/index2.htm
500 Can't connect to www.cursosdeprogramacionadistancia.com:80 (Bad hostname) http://www.cursosdeprogramacionadistancia.com/static/pdf/material-sin-personalizar-python.pdf

free-programming-books-bg.md

free-programming-books-ua.md

free-programming-books-pl.md

free-programming-books-fa_IR.md
500 Can't connect to laravel.ir:80 (Bad hostname) http://laravel.ir/

free-programming-books-ko.md

**Comment by onebree** [comment]
+1 for this issue. Maybe change the title to like "HELP WANTED: update broken URLs" so people realize it is for everyone/everything

**Comment by borgified** [comment]
hey cool, i didnt know checkboxes worked that way. ill have to update my script to automatically generate the checkboxes too (next time). big thank you for spearheading this effort to clean up the urls :heart:

**Comment by onebree** [comment]
@borgified I know the contributing guidelines would rather many small commits over 1 huge one... But right now my PR has 7 commits. Would it be best to do it such that it is 1 commit per changed file? I can squash them when I am ready.

**Comment by borgified** [comment]
np @onebree i think in this case since we doing maintenance rather than adding a new book, we don't necessarily have to adhere to that rule. most of your commits would be line deletions anyway so it's easy to enough to review.

**Comment by paraskevi26** [comment]
@borgified Hi, https://www.coursera.org/courses?orderby=upcoming&lngs=zh can load fine.

**Comment by borgified** [comment]
modified my url_checker script to include checkboxes https://github.com/borgified/url_checker/commit/fdb73a4cbe3c15d1797ebc1479c230d0d8db1ed1

**Comment by SanketDG** [comment]
Are you removing the books which are not available?

Because most of these is available from the web archive like,
https://web.archive.org/web/20150801005732/http://advancedlinuxprogramming.com/

**Comment by onebree** [comment]
I think for now we should not REMOVE anything, and instead just use archive links..

Another day, I am sure a script can be written that weeds out all web archive links.

**Comment by borgified** [comment]
well technically, even if we remove links, they are still in the commit history and we can always get them back... so they arent really "gone". we're just trying to lower the annoyance factor for users that come looking for books keep getting broken links instead.

**Comment by SanketDG** [comment]
@borgified That can be solved by putting in archive links?

**Comment by onebree** [comment]
@borgified please update the list, and cross out any of the ones I did.

**Comment by DavidMetcalfe** [comment]
Outstanding dead links inside of `free-programming-books.md` should be resolved now in PR #1681.

**Comment by DavidMetcalfe** [comment]
Additionally, there are two links with bad certificates (shown below), causing access issues to their pages. Do we have any recommendations on whether to remove them as dead links, or to preserve them?

* [Agda Tutorial](https://people.inf.elte.hu/divip/AgdaTutorial/Index.html)
* [Learn Markdown](https://www.gitbook.io/book/gitbookio/markdown) (PDF) (EPUB) (MOBI) - GitBookIO, Sammy P., Aaron O.

**Comment by eshellman** [comment]
Both the Agda tutorial and Learn Markdown work fine on http in stead of https. I know Aaron O. and will contact him about the cert.

**Comment by vhf** [comment]
Pong. I overlooked this issue, sorry about that :(. Here are some guidelines ideas we could discuss:

- always put `https` links instead of `http`
- if expired certificates/self-signed certificates/SSL issues of any kind:
  1. **replace it** with its `http` counterpart if possible (because accepting exceptions can be complicated on mobile devices)
  2. **leave it** if no `http` version but link still accessible through `https` by adding an exception to the browser or ignoring the warning
  3. **remove it** otherwise
- 404 links: **replace** with archive.org link but please:
  1. make sure the book is **free** (all books in this repo should be free and we are extra careful about this, but nothing is fool-proof, so checking again is also very important when replacing with an archive link)
  2. make sure **all the pages** are available (particularly important for HTML-format books split over many files sometimes deeply nested in a directory hierarchy -- IIRC it happens that archive.org stops crawling only a few directories deep)
  3. make sure **all assets** (images, PDFs, etc) are available
  4. only link to the **most recent** complete snapshot

Please tell me what you think of these proposed guidelines @onebree @DavidMetcalfe @eshellman et al.

(I like this archive.org idea. It raises an issue though: perhaps sometimes dead links are meant to be. I'll open an issue titled "Quantity ≠ Quality ≠ Relevancy" because I think it's a debate we should have, and a practical and satisfying solution might arise. I'll ping anyone I can think of!)

**Comment by DavidMetcalfe** [comment]
@eshellman Thanks. I've added a commit to adjust from `https` to `http`.

**Comment by onebree** [comment]
@vhf my thoughts on your proposal

**HTTP/S** - I agree that in any/all cases we should promote the HTTPS links. The only "issue" with this is that some sites, although they work in https, may default to http instead. I know this is not as common today, but I still see it, even with short or share links.

**404/archive** - I agree that linking to archive.org may not always be the answer. I think it is a good temp solution, in order to maintain the references we currently have until later review. I think we should limit how far back a archive snapshot should be. If the resource has been removed since 2013, it may be for good reason. I was also not aware of the fact archive.org limits its crawling depth (although it makes sense).

**More issues** - We should crack down on resources which stem from personal links (dropbox, drive) and aggregation sites. I notice this especially within the translated lists, possibly due to the lack of resources in that language. There was an issue recently (I think for PT language), but I cannot find the closed PR. Basically, even if these lists are not in your native language, it is easy to tell if they are not fully free/legal. (Google Translate helps too)

**Comment by vhf** [comment]
Thanks.

**HTTP/S**: Sure, removing an http link just because it's not https was never intended. But from now on, let's try to test every addition against https, and prefer https whenever possible.

**Personal links**: Good point. I opened #1683

**Aggregation sites**: Could you please elaborate on this point? I'm not sure to understand.

**Comment by onebree** [comment]
@vhf I cannot think of a better term for "aggregation" sites... But I basically mean a site where the doc is not hosted on an official website (maybe 4shared or something else), and there are big "DOWNLOAD NOW" buttons. I will try to look for the issue/PR I found this on for better explanation.

**Comment by onebree** [comment]
@vhf I cannot think of a better term for "aggregation" sites... But I basically mean a site where the doc is not hosted on an official website (maybe 4shared or something else), and there are big "DOWNLOAD NOW" buttons. Here is a PR that links to such site:

https://github.com/vhf/free-programming-books/pull/1439#issuecomment-150308146
