### ISSUE TITLE
Take care of all personal links (dropbox, google drive, etc)

### ISSUE THREAD

**Issue by vhf** [vhf/free-programming-books#1683]
Let's start with:

```
$ egrep -i "dl.dropbox|drive.google" *
free-programming-books-gr.md:* [Ένα byte της Python](https://dl.dropboxusercontent.com/u/54790396/a_byte_of_python-el.pdf)
free-programming-books-pt_BR.md:* [Desenvolvimento web com Python e web2py!](https://dl.dropboxusercontent.com/u/830444/apostila_web2py_basico.pdf)
free-programming-books-pt_BR.md:* [Tutorial de Ruby](http://dl.dropbox.com/u/1482800/eustaquiorangel.com/tutorialruby.pdf)
free-programming-books-pt_PT.md:* [C++ como uma linguagem de programação orientada a objectos](https://drive.google.com/open?id=0BwhtSmnYpzLdMEFrbDJsMDFDRFU&authuser=0) (PDF) - Autor desconhecido
free-programming-books-pt_PT.md:* [Apostilha de Java](https://drive.google.com/open?id=0BwhtSmnYpzLdWDNwV0k5N0RGaUk&authuser=0) (PDF) - Grupo PET Informática
free-programming-books-pt_PT.md:* [Introdução às Bases de Dados Oracle](https://drive.google.com/open?id=0BwhtSmnYpzLdRG9sdTNXVFp4Tzg&authuser=0) (PDF) - Pedro Bizarro, Universidade de Coimbra, 2008
free-programming-books-ru.md:* [Гибкие методологии разработки](https://dl.dropboxusercontent.com/u/4606839/Гибкие%20методологии%20разработки.pdf) - Вольфсон Борис
free-programming-books.md:* [Data Structures and Algorithms: Annotated Reference with Examples](https://drive.google.com/file/d/0B48k2jhdQ5P2aVlmMFB1UUJLczA/edit?usp=sharing)
free-programming-books.md:        * [Master Drupal in 7 hours](http://dl.dropboxusercontent.com/u/54624702/Master%20Drupal%20in%207%20hours_v1.1.pdf) (PDF)
```

Here is what I suggest:

1. As always, check if it's free.
2. Then find alternative link, ideally original source or author's website
3. If no good alternative link can be found, remove it anyway.

**Comment by onebree** [comment]
- `https://dl.dropboxusercontent.com/u/54790396/a_byte_of_python-el.pdf`
  + All links in the bib point to: http://www.swaroopch.com/mediawiki/index.php
  + Has creative Commons License (last page): http://creativecommons.org/licenses/by-sa/3.0/
  + Unsure if this is found elsewhere, since there is no listed author or title
- `https://dl.dropboxusercontent.com/u/830444/apostila_web2py_basico.pdf`
  + Unable to connect to official Brazil community site (http://www.web2pybrasil.com.br/)
  + Closest doc in PT: http://web2py.com/books/default/chapter/37
  + Official github repo: https://github.com/web2py/web2py/
- `https://dl.dropboxusercontent.com/u/1482800/eustaquiorangel.com/tutorialruby.pdf`
  + Creative Commons: http://creativecommons.org/licenses/by-nc-sa/3.0/deed.pt_BR
  + Official link (from author) pointing to download: http://eustaquiorangel.com/downloads
- `https://drive.google.com/file/d/0BwhtSmnYpzLdMEFrbDJsMDFDRFU/view`
  + No listed author, license, or CC
  + FWIW, there are no formatted code examples. They are all in sans-serif font without indentation.
- `https://drive.google.com/open?id=0BwhtSmnYpzLdWDNwV0k5N0RGaUk&authuser=0`
  + No author, license, CC
  + All references date prior to 2000
- `https://drive.google.com/open?id=0BwhtSmnYpzLdRG9sdTNXVFp4Tzg&authuser=0`
  + Includes author and date -- may be found online elsewhere
- `https://dl.dropboxusercontent.com/u/4606839/Гибкие%20методологии%20разработки.pdf`
  + Seems like a presentation
  + Includes (possible) authors' names and contact throughout
  + Extensive bibliography
  + I cannot tell if it includes licensing infomation
- `https://drive.google.com/file/d/0B48k2jhdQ5P2aVlmMFB1UUJLczA/edit?usp=sharing`
  + Originally downloaded from: http://dotnetslackers.com/projects/Data-Structures-And-Algorithms/
  + Copyright 2008 included
  + Inside the doc, says it was published exclusively for dotnetslackers
  + Also on scribd: https://www.scribd.com/doc/278944437/Data-Structures-and-Algorithms-Java
- `https://dl.dropboxusercontent.com/u/54624702/Master%20Drupal%20in%207%20hours_v1.1.pdf`
  + Copyright 2012 to author, see below:

    > Copyright © 2012 by Tuthanh Le
    > 
    > The contents of this book are the intellectual property of the author, who deserves to be compensated for the time and energy invested in this work.
    > 
    > Requests for permission to reproduce parts of this work should be addressed to the author. Contact information can be found on the book website:
    >
    > www.symphonythemes.com or www.tuthanh.com

  + Found on the last page of the book:

    > **Copyright**
    > This book is a commercial book. I do appreciate that you do not scan, upload or distribute this book via Internet or via any other means without the permissions from me.

**Comment by ajunior** [comment]
The following link on free-programming-books-pt_BR.md is broken:

Ruby: * [Pequeno Livro do Ruby](http://www.sismicro.com.br/ruby/Pequeno-Livro-do-Ruby.php)

**Comment by eshellman** [comment]
This is a translation of "A byte of Python",(CC BY)  in which is found this:
The Greek Ubuntu Community translated the book in Greek[13] , for use in our on-line asynchronous Python lessons that take place in our forums. Contact @savvasradevic for more information.



[13] http://wiki.ubuntu-gr.org/byte-of-python-el https://twitter.com/savvasradevic 

[14] https://twitter.com/savvasradevic
I will add the file to Internet Archive and provide a link in a PR.

http://wiki.ubuntu-gr.org/story/29-06-09/%CE%BC%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%B1-python-%CE%B3%CE%B9%CE%B1-%CE%B1%CF%81%CF%87%CE%AC%CF%81%CE%B9%CE%BF%CF%85%CF%82-%CF%83%CF%84%CE%BF-ubuntu-gr <http://wiki.ubuntu-gr.org/story/29-06-09/%CE%BC%CE%B1%CE%B8%CE%AE%CE%BC%CE%B1%CF%84%CE%B1-python-%CE%B3%CE%B9%CE%B1-%CE%B1%CF%81%CF%87%CE%AC%CF%81%CE%B9%CE%BF%CF%85%CF%82-%CF%83%CF%84%CE%BF-ubuntu-gr>
Eric Hellman
President, Free Ebook Foundation
Founder, Unglue.it https://unglue.it/
https://go-to-hellman.blogspot.com/
twitter: @gluejar

**Comment by vhf** [comment]
I may add a rule to the linter for this issue. If someone wants to help, you can provide regular expressions for dropbox URLs, google drive URLs, etc.

**Comment by jair2018** [comment]
copyright sucks
